In [1]:
from model.positional_encoding import PositionalEncoding
import torch
import math

In [2]:
seq_len = 20
d_model = 512
batch = 32

In [3]:
x1 = torch.zeros(seq_len, d_model)
x2 = torch.zeros(seq_len, d_model)

In [4]:
x1 == x2

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [5]:
pe_class = PositionalEncoding(d_model=d_model)

In [6]:
pe_class.calculate_pe(X=x1).shape

torch.Size([20, 512])

In [7]:
def sin(pos, i):
    return math.sin(pos/10000**(2*i/512))

def cos(pos, i):
    return math.cos(pos/10000**(2*i/512))

for i in range(20):
    for pos in range(512):
        if pos % 2 == 0:
            x2[i, pos] = sin(pos, i)
        else:
            x2[i, pos] = cos(pos, i)

In [10]:
x2

tensor([[ 0.0000,  0.5403,  0.9093,  ...,  0.9981,  0.8733, -0.4717],
        [ 0.0000,  0.5697,  0.9364,  ...,  0.6024,  0.9498, -0.9588],
        [ 0.0000,  0.5974,  0.9581,  ..., -0.7523, -0.2097, -0.4159],
        ...,
        [ 0.0000,  0.8564,  0.8843,  ...,  0.9416,  0.1978,  0.7374],
        [ 0.0000,  0.8662,  0.8657,  ..., -0.7800,  0.1522, -0.9322],
        [ 0.0000,  0.8753,  0.8466,  ...,  0.7875, -0.1586,  0.9409]])

In [13]:
pe_class.calculate_pe(X=x1)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  8.2186e-01,  ...,  1.0000e+00,
          1.0366e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  9.3641e-01,  ...,  1.0000e+00,
          2.0733e-04,  1.0000e+00],
        ...,
        [-9.6140e-01, -2.7516e-01, -6.3753e-01,  ...,  1.0000e+00,
          1.7623e-03,  1.0000e+00],
        [-7.5099e-01,  6.6032e-01, -9.9638e-01,  ...,  1.0000e+00,
          1.8659e-03,  1.0000e+00],
        [ 1.4988e-01,  9.8870e-01, -4.9773e-01,  ...,  1.0000e+00,
          1.9696e-03,  1.0000e+00]])